<?php
namespace Skonsoft\CompanyHierarchyBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends BaseRepository
{

}
