<?php

namespace Skonsoft\CompanyHierarchyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRepository extends EntityRepository
{
}
